import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/db';
import { users, contents, uploads, favorites, reviews, downloads, purchases, categories, settings, activity, messages, resets, sessions, announcements } from '@/db/schema';
import { eq, and, or, desc, sql } from 'drizzle-orm';
import { randomUUID, randomBytes, createHash } from 'crypto';
import { z } from 'zod';
import { fileTypeFromBuffer } from 'file-type';
import { getUser, requireUser, HttpError, checkOrigin, rateLimit, hashPassword, verifyPassword, createSession, logout, destination, adminRoles, creatorRoles, audit, digest } from '@/lib/auth';
import { ensureData } from '@/lib/seed';
import { getContent, getCategories, getCreators, getStats, getSettings, getDetail } from '@/lib/data';
import { storeFile, deliverFile } from '@/lib/storage';
const safeUrl=z.string().max(2000).refine(v=>{try{return ['https:','http:'].includes(new URL(v).protocol);}catch{return false;}},'Use a valid http or https URL.');
const contentSchema=z.object({title:z.string().min(3).max(150),description:z.string().min(10).max(300),body:z.string().min(20).max(50000),categoryId:z.string().min(1),thumbnail:z.string().max(2000).refine(v=>v.startsWith('/images/')||v.startsWith('/api/media/')||safeUrl.safeParse(v).success),version:z.string().max(40).default('1.0'),price:z.number().int().min(0).max(10000000).default(0),currency:z.enum(['USD','EUR','GBP','PKR']).default('USD'),tags:z.string().max(1000).default(''),uploadId:z.string().optional(),status:z.enum(['draft','pending','published','archived']).default('pending'),metadata:z.record(z.string().max(50),z.string().max(15000)).default({}),links:z.array(z.object({title:z.string().max(100),url:safeUrl,type:z.string().max(40)})).max(30).default([])});
export async function handle(req:NextRequest,context:{params:Promise<{path:string[]}>}){try{await ensureData();const {path}=await context.params;const route=path.join('/');const method=req.method;const p=req.nextUrl.searchParams;
 if(method!=='GET')checkOrigin(req);
 if(method==='GET'){
  if(route==='auth/me')return NextResponse.json({user:await getUser()});
  if(route==='content')return NextResponse.json(await getContent({type:p.get('type')||undefined,q:p.get('q')||undefined,category:p.get('category')||undefined,sort:p.get('sort')||undefined,offset:Math.max(0,Number(p.get('offset'))||0),limit:Math.min(60,Math.max(1,Number(p.get('limit'))||24))}));
  if(path[0]==='content'&&path[1]){const data=await getDetail(path[1]);if(!data)throw new HttpError(404,'Content not found.');const {file,...safe}=data;return NextResponse.json({...safe,file:file?{name:file.name,mime:file.mime,size:file.size}:null});}
  if(route==='categories')return NextResponse.json(await getCategories());
  if(route==='creators')return NextResponse.json(await getCreators());
  if(path[0]==='creators'&&path[1]){const creator=(await getCreators()).find(c=>c.username===path[1]);if(!creator)throw new HttpError(404,'Creator not found.');return NextResponse.json(creator);}
  if(['season','server','community'].includes(route))return NextResponse.json(await getSettings(route==='server'?'season':route));
  if(route==='favorites'){const user=await requireUser();return NextResponse.json(await db.select().from(favorites).where(eq(favorites.userId,user.id)));}
  if(route==='admin/stats'){await requireUser(adminRoles);return NextResponse.json(await getStats());}
  if(route==='admin/activity'){await requireUser(adminRoles);return NextResponse.json(await db.select().from(activity).orderBy(desc(activity.createdAt)).limit(100));}
  if(route==='admin/users'){await requireUser(adminRoles);return NextResponse.json(await db.select({id:users.id,name:users.name,username:users.username,email:users.email,role:users.role,suspended:users.suspended,createdAt:users.createdAt}).from(users));}
  if(path[0]==='download'&&path[1]){
   await rateLimit(req,'download',100);const [item]=await db.select().from(contents).where(and(eq(contents.id,path[1]),eq(contents.status,'published')));if(!item||!item.uploadId)throw new HttpError(404,'This file is not available.');const user=await getUser();if(item.price>0){if(!user)throw new HttpError(401,'Please log in to access your purchases.');const [order]=await db.select().from(purchases).where(and(eq(purchases.contentId,item.id),eq(purchases.userId,user.id),eq(purchases.status,'paid')));if(!order&&user.id!==item.creatorId&&!adminRoles.includes(user.role))throw new HttpError(403,'A verified purchase is required.');}
   const [file]=await db.select().from(uploads).where(eq(uploads.id,item.uploadId));if(!file)throw new HttpError(404,'File not found.');const response=await deliverFile(file.key,file.name,file.mime);await db.transaction(async tx=>{await tx.insert(downloads).values({id:randomUUID(),userId:user?.id,contentId:item.id});await tx.update(contents).set({downloads:sql`${contents.downloads}+1`}).where(eq(contents.id,item.id));});return response;
  }
  if(path[0]==='media'&&path[1]){const [file]=await db.select().from(uploads).where(eq(uploads.id,path[1]));if(!file||!['image/png','image/jpeg','image/webp','image/gif'].includes(file.mime))throw new HttpError(404,'Image not found.');const [paid]=await db.select({id:contents.id}).from(contents).where(and(eq(contents.uploadId,file.id),sql`${contents.price}>0`));if(paid)throw new HttpError(403,'Protected resource.');const [preview]=await db.select({id:contents.id}).from(contents).where(and(eq(contents.thumbnail,'/api/media/'+file.id),eq(contents.status,'published')));if(!preview){const user=await requireUser();if(user.id!==file.userId&&!adminRoles.includes(user.role))throw new HttpError(403,'This preview is private.');}return deliverFile(file.key,file.name,file.mime);}
 }
 if(method==='POST'){
  if(route==='upload'){
   const user=await requireUser(creatorRoles);await rateLimit(req,'upload',80);const max=Number(process.env.MAX_UPLOAD_BYTES)||104857600;if(Number(req.headers.get('content-length'))>max+1048576)throw new HttpError(413,'File exceeds the server upload limit.');const form=await req.formData();const file=form.get('file');if(!(file instanceof File)||file.size===0)throw new HttpError(400,'Select a non-empty file.');if(file.size>max)throw new HttpError(413,'File exceeds the server upload limit.');const name=file.name.replace(/[^a-zA-Z0-9._-]/g,'_').slice(-180);const ext=name.split('.').pop()?.toLowerCase()||'';const allowed=['zip','rar','7z','jar','mcworld','mcaddon','mcpack','png','jpg','jpeg','webp','gif','mp4','webm','mp3','wav','ogg','pdf','txt','md','csv','json','js','ts','tsx','jsx','css','html','py','java','yml','yaml','xml','docx','xlsx','pptx','blend','psd','svg','obj'];if(!allowed.includes(ext))throw new HttpError(400,'This file type is not supported.');const buffer=Buffer.from(await file.arrayBuffer());const detected=await fileTypeFromBuffer(buffer);const textTypes=['txt','md','csv','json','js','ts','tsx','jsx','css','html','py','java','yml','yaml','xml','svg','obj'];if(!detected&&!textTypes.includes(ext)&&ext!=='blend')throw new HttpError(400,'The file signature could not be verified.');if(detected&&['exe','dll','elf','msi'].includes(detected.ext))throw new HttpError(400,'Executable binaries are not accepted.');const groups:Record<string,string[]>= {png:['png'],jpg:['jpg'],jpeg:['jpg'],webp:['webp'],gif:['gif'],pdf:['pdf'],zip:['zip'],jar:['zip'],mcworld:['zip'],mcaddon:['zip'],mcpack:['zip'],rar:['rar'],'7z':['7z']};if(groups[ext]&&(!detected||!groups[ext].includes(detected.ext)))throw new HttpError(400,'File extension does not match its contents.');if(!detected&&buffer.includes(0)&&ext!=='blend')throw new HttpError(400,'Invalid text file.');const id=randomUUID(),key=id+'.'+ext,mime=detected?.mime||'application/octet-stream';await storeFile(key,buffer,mime);await db.insert(uploads).values({id,userId:user.id,key,name,mime,size:file.size,hash:createHash('sha256').update(buffer).digest('hex')});await audit(user.id,'upload',name);return NextResponse.json({id,name,mime,size:file.size,url:'/api/media/'+id});
  }
  const body=await req.json();
  if(route==='auth/register'){
   await rateLimit(req,'register',8);const data=z.object({name:z.string().min(2).max(80),username:z.string().min(3).max(30).regex(/^[a-zA-Z0-9_-]+$/),email:z.email(),password:z.string().min(10).max(128),confirmPassword:z.string(),terms:z.literal(true)}).refine(d=>d.password===d.confirmPassword,{message:'Passwords do not match.'}).parse(body);const email=data.email.toLowerCase(),username=data.username.toLowerCase();const [exists]=await db.select({id:users.id}).from(users).where(or(eq(users.email,email),eq(users.username,username)));if(exists)throw new HttpError(409,'An account with this email or username already exists.');const id=randomUUID();await db.insert(users).values({id,name:data.name,username,email,password:await hashPassword(data.password)});await createSession(id);await audit(id,'register');return NextResponse.json({redirect:'/dashboard'});
  }
  if(route==='auth/login'){await rateLimit(req,'login',15);const data=z.object({email:z.string().min(1),password:z.string().max(128),remember:z.boolean().optional()}).parse(body);const login=data.email.toLowerCase();const [user]=await db.select().from(users).where(or(eq(users.email,login),eq(users.username,login)));if(!user||!await verifyPassword(data.password,user.password)||user.suspended)throw new HttpError(401,'The email or password is incorrect.');await createSession(user.id,data.remember);await audit(user.id,'login');return NextResponse.json({redirect:destination(user.role)});}
  if(route==='auth/logout'){await logout();return NextResponse.json({ok:true});}
  if(route==='auth/forgot-password'){await rateLimit(req,'reset',5);const {email}=z.object({email:z.email()}).parse(body);if(!process.env.RESEND_API_KEY||!process.env.EMAIL_FROM)throw new HttpError(503,'Password reset email is not configured. Contact homelandgang@gmail.com for help.');const [user]=await db.select().from(users).where(eq(users.email,email.toLowerCase()));if(user){const token=randomBytes(32).toString('hex');await db.insert(resets).values({token:digest(token),userId:user.id,expiresAt:new Date(Date.now()+1800000)});const url=`${process.env.NEXT_PUBLIC_SITE_URL||req.headers.get('origin')||req.nextUrl.origin}/reset-password?token=${token}`;const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:process.env.EMAIL_FROM,to:[user.email],subject:'Reset your HOMELAND password',text:`Reset your password using this link within 30 minutes: ${url}\nIf you did not request this, ignore this email.`})});if(!response.ok)throw new HttpError(503,'Email delivery is temporarily unavailable.');}return NextResponse.json({message:'If an account exists, a password reset link has been sent.'});}
  if(route==='auth/reset-password'){await rateLimit(req,'reset-submit',10);const data=z.object({token:z.string().min(32),password:z.string().min(10).max(128),confirmPassword:z.string()}).refine(v=>v.password===v.confirmPassword,{message:'Passwords do not match.'}).parse(body);const password=await hashPassword(data.password);await db.transaction(async tx=>{const [reset]=await tx.delete(resets).where(and(eq(resets.token,digest(data.token)),sql`${resets.expiresAt}>now()`)).returning();if(!reset)throw new HttpError(400,'This reset link has expired or has already been used.');await tx.update(users).set({password}).where(eq(users.id,reset.userId));await tx.delete(sessions).where(eq(sessions.userId,reset.userId));});return NextResponse.json({redirect:'/login'});}
  if(route==='creator/join'){const user=await requireUser();if(user.role==='USER'){await db.update(users).set({role:'CREATOR'}).where(eq(users.id,user.id));await audit(user.id,'creator.join');}return NextResponse.json({redirect:destination(user.role==='USER'?'CREATOR':user.role)});}
  if(route==='favorites'){const user=await requireUser();const {contentId}=z.object({contentId:z.string()}).parse(body);const [item]=await db.select({id:contents.id}).from(contents).where(and(eq(contents.id,contentId),eq(contents.status,'published')));if(!item)throw new HttpError(404,'Content not found.');const [existing]=await db.select().from(favorites).where(and(eq(favorites.userId,user.id),eq(favorites.contentId,contentId)));if(existing)await db.delete(favorites).where(eq(favorites.id,existing.id));else await db.insert(favorites).values({id:randomUUID(),userId:user.id,contentId}).onConflictDoNothing();return NextResponse.json({saved:!existing});}
  if(route==='reviews'){const user=await requireUser();await rateLimit(req,'review',20);const data=z.object({contentId:z.string(),rating:z.number().int().min(1).max(5),comment:z.string().min(3).max(2000)}).parse(body);const [item]=await db.select().from(contents).where(and(eq(contents.id,data.contentId),eq(contents.status,'published')));if(!item)throw new HttpError(404,'Content not found.');await db.insert(reviews).values({id:randomUUID(),userId:user.id,...data}).onConflictDoUpdate({target:[reviews.userId,reviews.contentId],set:{rating:data.rating,comment:data.comment}});return NextResponse.json({message:'Your review has been saved.'});}
  if(route==='purchase'){await requireUser();throw new HttpError(503,'Purchasing is currently unavailable. No payment has been taken.');}
  if(route==='contact'){await rateLimit(req,'contact',5);const data=z.object({name:z.string().min(2).max(80),email:z.email(),subject:z.string().min(3).max(150),message:z.string().min(10).max(5000)}).parse(body);await db.insert(messages).values({id:randomUUID(),...data});return NextResponse.json({message:'Message received. Thank you for reaching out to HOMELAND.'});}
  if(route==='content'){const user=await requireUser(creatorRoles);const data=contentSchema.parse(body);if(data.uploadId){const [file]=await db.select().from(uploads).where(eq(uploads.id,data.uploadId));if(!file||file.userId!==user.id&&!adminRoles.includes(user.role))throw new HttpError(403,'This file does not belong to you.');}if(!adminRoles.includes(user.role)&&data.status==='published')data.status='pending';const id=randomUUID();const slug=data.title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+id.slice(0,6);await db.insert(contents).values({...data,id,slug,creatorId:user.id});await audit(user.id,'content.create',data.title);return NextResponse.json({id,slug,message:data.status==='draft'?'Draft saved.':'Content submitted for review.'});}
  if(route==='categories'){const user=await requireUser(adminRoles);const data=z.object({name:z.string().min(2).max(80),description:z.string().max(300),icon:z.string().default('grid'),position:z.number().int().default(0)}).parse(body);await db.insert(categories).values({id:randomUUID(),...data});await audit(user.id,'category.create',data.name);return NextResponse.json({ok:true});}
  if(route==='announcements'){const user=await requireUser(adminRoles);const data=z.object({title:z.string().min(3).max(180),body:z.string().min(10).max(10000),section:z.enum(['community','smp'])}).parse(body);await db.insert(announcements).values({id:randomUUID(),...data});await audit(user.id,'announcement.create',data.title);return NextResponse.json({ok:true});}
 }
 if(method==='PUT'){
  const body=await req.json();
  if(route==='profile'){const user=await requireUser();const data=z.object({name:z.string().min(2).max(80),bio:z.string().max(2000)}).parse(body);await db.update(users).set(data).where(eq(users.id,user.id));return NextResponse.json({message:'Profile updated.'});}
  if(path[0]==='content'&&path[1]){const user=await requireUser(creatorRoles);const [item]=await db.select().from(contents).where(eq(contents.id,path[1]));if(!item)throw new HttpError(404,'Content not found.');if(item.creatorId!==user.id&&!adminRoles.includes(user.role)&&user.role!=='EDITOR')throw new HttpError(403,'You cannot edit this content.');const data=contentSchema.partial().extend({featured:z.boolean().optional(),creatorId:z.string().optional()}).parse(body);if(!adminRoles.includes(user.role)){delete data.featured;delete data.creatorId;if(data.status==='published')data.status='pending';}if(data.uploadId){const [file]=await db.select().from(uploads).where(eq(uploads.id,data.uploadId));if(!file||file.userId!==user.id&&!adminRoles.includes(user.role))throw new HttpError(403,'This file does not belong to you.');}await db.update(contents).set(data).where(eq(contents.id,item.id));await audit(user.id,'content.update',item.title);return NextResponse.json({message:'Content updated.'});}
  if(path[0]==='admin'&&path[1]==='users'&&path[2]){const user=await requireUser(adminRoles);const data=z.object({role:z.enum(['OWNER','ADMIN','CREATOR','EDITOR','MODERATOR','USER']).optional(),suspended:z.boolean().optional()}).parse(body);const [target]=await db.select().from(users).where(eq(users.id,path[2]));if(!target)throw new HttpError(404,'User not found.');if(target.id===user.id||target.role==='OWNER'||(user.role!=='OWNER'&&(target.role==='ADMIN'||['ADMIN','OWNER'].includes(data.role||''))))throw new HttpError(403,'Only an owner may manage privileged roles. You cannot modify yourself.');await db.update(users).set(data).where(eq(users.id,target.id));await db.delete(sessions).where(eq(sessions.userId,target.id));await audit(user.id,'user.update',target.username);return NextResponse.json({ok:true});}
  if(path[0]==='settings'||['season','server'].includes(route)){const user=await requireUser(adminRoles);const key=path[0]==='settings'?path[1]:'season';if(!['homepage','season','community','faq','footer'].includes(key))throw new HttpError(400,'Unknown settings section.');if(JSON.stringify(body).length>50000)throw new HttpError(400,'Settings are too large.');for(const name of ['discord','youtube','trailer'])if(body[name]&&!safeUrl.safeParse(body[name]).success)throw new HttpError(400,`${name} must be a valid URL.`);await db.insert(settings).values({key,value:body}).onConflictDoUpdate({target:settings.key,set:{value:body}});await audit(user.id,'settings.update',key);return NextResponse.json({message:'Settings saved.'});}
  if(path[0]==='categories'&&path[1]){const user=await requireUser(adminRoles);const data=z.object({name:z.string().min(2).max(80),description:z.string().max(300),icon:z.string().max(40),position:z.number().int()}).partial().parse(body);await db.update(categories).set(data).where(eq(categories.id,path[1]));await audit(user.id,'category.update',path[1]);return NextResponse.json({ok:true});}
 }
 if(method==='DELETE'){
  if(path[0]==='content'&&path[1]){const user=await requireUser(creatorRoles);const [item]=await db.select().from(contents).where(eq(contents.id,path[1]));if(!item)throw new HttpError(404,'Content not found.');if(item.creatorId!==user.id&&!adminRoles.includes(user.role))throw new HttpError(403,'You cannot delete this content.');
   // permanent=true → hard delete (admin-only)
   if(p.get('permanent')==='true'){
     if(!adminRoles.includes(user.role))throw new HttpError(403,'Only admins can permanently delete content.');
     await db.transaction(async tx=>{
       await tx.delete(favorites).where(eq(favorites.contentId,item.id));
       await tx.delete(reviews).where(eq(reviews.contentId,item.id));
       await tx.delete(downloads).where(eq(downloads.contentId,item.id));
       await tx.delete(contents).where(eq(contents.id,item.id));
     });
     await audit(user.id,'content.delete',item.title);
     return NextResponse.json({ok:true,message:'Resource permanently deleted.'});
   }
   // default → soft archive
   await db.update(contents).set({status:'archived'}).where(eq(contents.id,item.id));await audit(user.id,'content.archive',item.title);return NextResponse.json({ok:true});}
  if(path[0]==='categories'&&path[1]){const user=await requireUser(adminRoles);const [linked]=await db.select({id:contents.id}).from(contents).where(eq(contents.categoryId,path[1]));if(linked)throw new HttpError(409,'Move content to another category before deleting this one.');await db.delete(categories).where(eq(categories.id,path[1]));await audit(user.id,'category.delete',path[1]);return NextResponse.json({ok:true});}
  if(path[0]==='reviews'&&path[1]){const user=await requireUser();const [review]=await db.select().from(reviews).where(eq(reviews.id,path[1]));if(!review)throw new HttpError(404,'Review not found.');if(review.userId!==user.id&&!['OWNER','ADMIN','MODERATOR'].includes(user.role))throw new HttpError(403,'Not allowed.');await db.delete(reviews).where(eq(reviews.id,review.id));return NextResponse.json({ok:true});}
 }
 throw new HttpError(404,'Endpoint not found.');
 }catch(error){if(error instanceof HttpError)return NextResponse.json({error:error.message},{status:error.status});if(error instanceof z.ZodError)return NextResponse.json({error:error.issues[0]?.message||'Invalid input.'},{status:400});console.error('API error',error);return NextResponse.json({error:'Something went wrong. Please try again.'},{status:500});}}
