import { db } from '@/db';
import { contents, categories, users, settings, reviews, uploads, downloads, favorites, purchases } from '@/db/schema';
import { eq, and, or, ilike, desc, asc, sql, count } from 'drizzle-orm';
import { ensureData } from './seed';
export type ContentItem = Awaited<ReturnType<typeof getContent>>[number];
export async function getContent(filters:{type?:string;q?:string;category?:string;creator?:string;sort?:string;limit?:number;offset?:number;all?:boolean}={}){await ensureData();const where=[];if(!filters.all)where.push(eq(contents.status,'published'));if(filters.type==='free')where.push(eq(contents.price,0));if(filters.type==='paid')where.push(sql`${contents.price}>0`);if(filters.category)where.push(eq(contents.categoryId,filters.category));if(filters.creator)where.push(eq(contents.creatorId,filters.creator));if(filters.q)where.push(or(ilike(contents.title,`%${filters.q}%`),ilike(contents.tags,`%${filters.q}%`),ilike(contents.description,`%${filters.q}%`),ilike(users.name,`%${filters.q}%`),ilike(categories.name,`%${filters.q}%`)));return db.select({id:contents.id,slug:contents.slug,title:contents.title,description:contents.description,body:contents.body,thumbnail:contents.thumbnail,price:contents.price,currency:contents.currency,version:contents.version,downloads:contents.downloads,views:contents.views,featured:contents.featured,status:contents.status,categoryId:contents.categoryId,category:categories.name,creatorId:users.id,creator:users.name,username:users.username,metadata:contents.metadata,links:contents.links,tags:contents.tags,uploadId:contents.uploadId,createdAt:contents.createdAt,rating:sql<number>`coalesce((select avg(rating) from reviews where content_id=${contents.id}),0)`.mapWith(Number),reviewCount:sql<number>`(select count(*) from reviews where content_id=${contents.id})`.mapWith(Number)}).from(contents).innerJoin(users,eq(contents.creatorId,users.id)).innerJoin(categories,eq(contents.categoryId,categories.id)).where(and(...where)).orderBy(filters.sort==='popular'?desc(contents.downloads):filters.sort==='rating'?sql`coalesce((select avg(rating) from reviews where content_id=${contents.id}),0) DESC`:filters.sort==='latest'?desc(contents.createdAt):asc(contents.createdAt)).limit(filters.limit||60).offset(filters.offset||0);}
export async function getCategories(){await ensureData();return db.select({id:categories.id,name:categories.name,description:categories.description,icon:categories.icon,position:categories.position,count:sql<number>`(select count(*) from contents where category_id=${categories.id} and status='published')`.mapWith(Number)}).from(categories).orderBy(asc(categories.position));}
export async function getCreators(){await ensureData();return db.select({id:users.id,name:users.name,username:users.username,bio:users.bio,role:users.role,avatar:users.avatar,uploads:sql<number>`(select count(*) from contents where creator_id=${users.id} and status='published')`.mapWith(Number),downloads:sql<number>`coalesce((select sum(downloads) from contents where creator_id=${users.id} and status='published'),0)`.mapWith(Number)}).from(users).where(and(sql`${users.role} in ('CREATOR','OWNER','ADMIN')`,eq(users.suspended,false)));}
export async function getSettings(key:string){await ensureData();const [s]=await db.select().from(settings).where(eq(settings.key,key));return s?.value||{};}
export async function getStats(){await ensureData();const [content]=await db.select({total:count(),downloads:sql<number>`coalesce(sum(${contents.downloads}),0)`.mapWith(Number),views:sql<number>`coalesce(sum(${contents.views}),0)`.mapWith(Number),free:sql<number>`count(*) filter(where price=0)`.mapWith(Number),paid:sql<number>`count(*) filter(where price>0)`.mapWith(Number)}).from(contents).where(eq(contents.status,'published'));const [u]=await db.select({total:count(),creators:sql<number>`count(*) filter(where role in ('CREATOR','ADMIN','OWNER'))`.mapWith(Number)}).from(users).where(eq(users.suspended,false));return {...content,users:u.total,creators:u.creators};}
export async function getDetail(slug:string){const all=await getContent();const item=all.find(c=>c.slug===slug);if(!item)return null;const feedback=await db.select({id:reviews.id,rating:reviews.rating,comment:reviews.comment,name:users.name,createdAt:reviews.createdAt}).from(reviews).innerJoin(users,eq(reviews.userId,users.id)).where(eq(reviews.contentId,item.id));const [file]=item.uploadId?await db.select().from(uploads).where(eq(uploads.id,item.uploadId)):[];return {item,feedback,file};}
export async function getLibrary(userId:string){const [saved,history,orders]=await Promise.all([db.select({id:favorites.contentId}).from(favorites).where(eq(favorites.userId,userId)),db.select({id:downloads.contentId,at:downloads.createdAt}).from(downloads).where(eq(downloads.userId,userId)).orderBy(desc(downloads.createdAt)),db.select().from(purchases).where(and(eq(purchases.userId,userId),eq(purchases.status,'paid')))]);return {saved,history,orders};}
