import 'dotenv/config';
import { chromium } from '@playwright/test';
import { randomBytes,createHash,randomUUID } from 'crypto';
import { db,pool } from '@/db';
import { users,sessions,contents,categories,settings,announcements } from '@/db/schema';
import { ilike,eq } from 'drizzle-orm';
async function main(){const [user]=await db.select().from(users).where(ilike(users.username,'smoke_%'));if(!user)throw new Error('Run browser smoke test first.');await db.update(users).set({role:'OWNER'}).where(eq(users.id,user.id));const token=randomBytes(32).toString('hex');await db.insert(sessions).values({id:createHash('sha256').update(token).digest('hex'),userId:user.id,expiresAt:new Date(Date.now()+3600000)});const browser=await chromium.launch({headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1000}});await page.context().addCookies([{name:'homeland_session',value:token,domain:'localhost',path:'/',httpOnly:true,secure:false,sameSite:'Lax'}]);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:3000/admin');await page.getByRole('heading',{name:'HOMELAND CREATOR PANEL'}).waitFor();console.log('Admin dashboard role check passed');await page.goto('http://localhost:3000/admin?tab=pending');await page.getByRole('button',{name:'Publish resource',exact:true}).click();await page.getByText('Content updated.').waitFor();const [item]=await db.select().from(contents).where(eq(contents.creatorId,user.id));if(item.status!=='published')throw new Error('Admin publish did not persist');await page.goto('http://localhost:3000/stuff/'+item.slug);await page.getByRole('heading',{name:item.title,exact:true}).waitFor();console.log('Pending approval and public publishing passed');
const original=(await db.select().from(settings).where(eq(settings.key,'homepage')))[0].value;await page.goto('http://localhost:3000/admin?tab=homepage');const description=page.locator('#settings-description').first();await description.fill('Smoke test homepage message — restored immediately after verification.');await page.getByRole('button',{name:'Save settings',exact:true}).first().click();await page.getByText('Your changes are live.').waitFor();const changed=(await db.select().from(settings).where(eq(settings.key,'homepage')))[0].value;if(!String(changed.description).startsWith('Smoke test'))throw new Error('CMS update failed');await db.update(settings).set({value:original}).where(eq(settings.key,'homepage'));console.log('Homepage CMS database update and restoration passed');
const origin={Origin:'http://localhost:3000'};let r=await page.request.post('http://localhost:3000/api/categories',{headers:origin,data:{name:'Smoke category '+user.id.slice(0,5),description:'Temporary test category.',icon:'grid',position:99}});if(!r.ok())throw new Error(await r.text());const [cat]=await db.select().from(categories).where(ilike(categories.name,'Smoke category%'));r=await page.request.put('http://localhost:3000/api/categories/'+cat.id,{headers:origin,data:{name:'Smoke category edited',position:98}});if(!r.ok())throw new Error(await r.text());r=await page.request.delete('http://localhost:3000/api/categories/'+cat.id,{headers:origin});if(!r.ok())throw new Error(await r.text());console.log('Category create/edit/delete passed');
r=await page.request.post('http://localhost:3000/api/announcements',{headers:origin,data:{title:'Smoke announcement',body:'A temporary test announcement that is removed after verification.',section:'community'}});if(!r.ok())throw new Error(await r.text());await db.delete(announcements).where(eq(announcements.title,'Smoke announcement'));console.log('Community announcement persistence passed');
r=await page.request.post('http://localhost:3000/api/contact',{headers:origin,data:{name:'Smoke Test',email:user.email,subject:'Smoke contact message',message:'A test of real contact form persistence.'}});if(!r.ok())throw new Error(await r.text());console.log('Contact inbox persistence passed');
const evil=new FormData();evil.append('file',new Blob(['not a PNG file'],{type:'image/png'}),'disguised.png');const bad=await page.evaluate(async()=>{const form=new FormData();form.append('file',new Blob(['not a PNG file'],{type:'image/png'}),'disguised.png');const r=await fetch('/api/upload',{method:'POST',body:form});return {status:r.status,body:await r.json()};});if(bad.status!==400)throw new Error('File signature check failed');console.log('Disguised upload rejected',bad.status);
for(const tab of ['content','users','categories','downloads','orders','season','community','activity','inbox','settings']){await page.goto('http://localhost:3000/admin?tab='+tab);if(await page.getByText('A little bump in the road.').count())throw new Error('Admin tab failed '+tab);}
await page.goto('http://localhost:3000/admin');await page.screenshot({path:'artifacts/admin-desktop.png',fullPage:true});console.log('All admin tabs rendered. Browser errors:',errors);await browser.close();await pool.end();if(errors.length)process.exitCode=1;}
main().catch(e=>{console.error(e);process.exit(1)});
