import { chromium } from '@playwright/test';
import { randomBytes } from 'node:crypto';
import { mkdir } from 'node:fs/promises';
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1080}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',async r=>{if(r.url().includes('/api/')&&r.status()>=400)console.log('API FAILURE',r.status(),r.url(),await r.text());});
await mkdir('artifacts',{recursive:true});
await page.goto('http://localhost:3000',{waitUntil:'networkidle'});
await page.screenshot({path:'artifacts/home-desktop.png',fullPage:true});
console.log('Desktop homepage',await page.title(),'overflow',await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth));
await page.getByRole('link',{name:'Explore Free Stuff',exact:true}).first().click();
await page.waitForURL('**/free');
await page.getByRole('textbox',{name:'Search resources',exact:true}).fill('Aurora');
console.log('Search cards',await page.locator('.content-card').count());
await page.goto('http://localhost:3000/register');
const suffix=randomBytes(5).toString('hex');const username='smoke_'+suffix;const password=randomBytes(18).toString('base64url')+'Aa1';
await page.getByLabel('Your name',{exact:true}).fill('Smoke Test Creator');
await page.getByLabel('Username',{exact:true}).fill(username);
await page.getByLabel('Email address',{exact:true}).fill(username+'@example.test');
await page.getByLabel('Password',{exact:true}).fill(password);
await page.getByLabel('Confirm password',{exact:true}).fill(password);
await page.locator('input[name=terms]').check();
await page.getByRole('button',{name:'Create your account'}).click();
await page.waitForURL('**/dashboard').catch(async e=>{await page.screenshot({path:'artifacts/registration-failure.png',fullPage:true});console.log('Registration page',page.url(),await page.locator('form').innerText(),errors);throw e;});console.log('Registration and redirect passed');
const me=await page.request.get('http://localhost:3000/api/auth/me');const user=(await me.json()).user;
if(!user)throw new Error('Session was not persisted');
const forbidden=await page.request.get('http://localhost:3000/api/admin/stats');if(forbidden.status()!==403)throw new Error('Normal user can access admin stats');console.log('User admin denial',forbidden.status());
await page.getByRole('button',{name:'Become a Creator'}).click();await page.waitForURL('**/creator');console.log('Creator onboarding passed');
await page.goto('http://localhost:3000/creator?tab=upload');
await page.locator('input[type=file]').first().setInputFiles({name:'smoke-resource.txt',mimeType:'text/plain',buffer:Buffer.from('Original test resource. Created only for end-to-end validation.')});
await page.getByLabel('Content name',{exact:true}).waitFor();
await page.getByLabel('Content name',{exact:true}).fill('Smoke resource '+suffix);
await page.getByLabel('Short description',{exact:true}).fill('A temporary resource for end-to-end validation.');
await page.getByLabel('Full description',{exact:true}).fill('This resource is created by the automated smoke test and is deleted immediately afterward.');
await page.getByRole('button',{name:'Submit for review'}).click();
await page.waitForURL('**/creator?tab=content');console.log('Upload and review submission passed');
await page.goto('http://localhost:3000/stuff/aurora');
await page.getByLabel('Your review',{exact:true}).fill('Automated validation review. This record will be removed.');
await page.getByRole('button',{name:'Post review'}).click();
await page.getByText('Your review has been saved.').waitFor();console.log('Review persistence passed');
const favorite=await page.request.post('http://localhost:3000/api/favorites',{headers:{Origin:'http://localhost:3000'},data:{contentId:'aurora'}});if(!favorite.ok())throw new Error(await favorite.text());
await page.goto('http://localhost:3000/favorites');console.log('Favorites persisted',await page.locator('.content-card').count());
const download=await page.request.get('http://localhost:3000/api/download/aurora');if(!download.ok()||(await download.body()).length<1000)throw new Error('Download failed');console.log('Actual download passed',download.headers()['content-disposition']);
const paid=await page.request.get('http://localhost:3000/api/download/chromatic');if(paid.status()!==403)throw new Error('Paid download authorization failed');console.log('Paid access denial',paid.status());
const csrf=await page.request.post('http://localhost:3000/api/favorites',{headers:{Origin:'https://evil.invalid'},data:{contentId:'aurora'}});if(csrf.status()!==403)throw new Error('CSRF origin boundary failed');console.log('Cross-origin mutation rejected');
await page.getByRole('button',{name:'Log out'}).click();
await page.waitForURL('http://localhost:3000/');
await page.goto('http://localhost:3000/login');
await page.getByLabel('Email or username').fill(username);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Login to HOMELAND'}).click();await page.waitForURL('**/creator');console.log('Logout and creator login redirect passed');
await page.screenshot({path:'artifacts/creator-desktop.png',fullPage:true});
const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
await mobile.goto('http://localhost:3000',{waitUntil:'networkidle'});await mobile.screenshot({path:'artifacts/home-mobile.png',fullPage:true});
console.log('Mobile overflow',await mobile.evaluate(()=>document.documentElement.scrollWidth>innerWidth));
await mobile.getByRole('button',{name:'Open menu'}).click();await mobile.getByRole('navigation',{name:'Mobile navigation'}).getByRole('link',{name:'Free Stuff'}).click();await mobile.waitForURL('**/free');console.log('Mobile navigation passed');
console.log('Browser errors',JSON.stringify(errors));console.log('TEST_USER',user.id,username);
await browser.close();
if(errors.length)process.exitCode=1;
