import { pgTable, text, timestamp, integer, boolean, jsonb, uniqueIndex } from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
 id: text('id').primaryKey(), name: text('name').notNull(), username: text('username').notNull().unique(), email: text('email').notNull().unique(), password: text('password').notNull(), role: text('role').notNull().default('USER'), bio: text('bio').notNull().default(''), avatar: text('avatar'), suspended: boolean('suspended').notNull().default(false), createdAt: timestamp('created_at').defaultNow().notNull(),
});
export const sessions = pgTable('sessions', { id: text('id').primaryKey(), userId: text('user_id').notNull().references(() => users.id, {onDelete:'cascade'}), expiresAt: timestamp('expires_at').notNull() });
export const categories = pgTable('categories', { id: text('id').primaryKey(), name: text('name').notNull().unique(), description: text('description').notNull(), icon: text('icon').notNull(), position: integer('position').notNull().default(0) });
export const uploads = pgTable('uploads', { id: text('id').primaryKey(), userId: text('user_id').notNull().references(()=>users.id), key: text('key').notNull(), name: text('name').notNull(), mime: text('mime').notNull(), size: integer('size').notNull(), hash: text('hash').notNull(), createdAt: timestamp('created_at').defaultNow().notNull() });
export const contents = pgTable('contents', {
 id: text('id').primaryKey(), slug: text('slug').notNull().unique(), title: text('title').notNull(), description: text('description').notNull(), body: text('body').notNull(), thumbnail: text('thumbnail').notNull(), creatorId: text('creator_id').notNull().references(()=>users.id), categoryId: text('category_id').notNull().references(()=>categories.id), version: text('version').notNull().default('1.0'), price: integer('price').notNull().default(0), currency: text('currency').notNull().default('USD'), status: text('status').notNull().default('draft'), featured: boolean('featured').notNull().default(false), uploadId: text('upload_id').references(()=>uploads.id), downloads: integer('downloads').notNull().default(0), views: integer('views').notNull().default(0), tags: text('tags').notNull().default(''), metadata: jsonb('metadata').$type<Record<string, string>>().notNull().default({}), links: jsonb('links').$type<{title:string;url:string;type:string}[]>().notNull().default([]), createdAt: timestamp('created_at').notNull().defaultNow(),
});
export const favorites = pgTable('favorites', { id: text('id').primaryKey(), userId: text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}), contentId: text('content_id').notNull().references(()=>contents.id,{onDelete:'cascade'}), createdAt:timestamp('created_at').defaultNow().notNull() }, t=>[uniqueIndex('favorite_unique').on(t.userId,t.contentId)]);
export const reviews = pgTable('reviews', { id:text('id').primaryKey(), userId:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}), contentId:text('content_id').notNull().references(()=>contents.id,{onDelete:'cascade'}), rating:integer('rating').notNull(), comment:text('comment').notNull(), createdAt:timestamp('created_at').defaultNow().notNull() },t=>[uniqueIndex('review_unique').on(t.userId,t.contentId)]);
export const downloads = pgTable('downloads', {id:text('id').primaryKey(),userId:text('user_id').references(()=>users.id,{onDelete:'set null'}),contentId:text('content_id').notNull().references(()=>contents.id,{onDelete:'cascade'}),createdAt:timestamp('created_at').defaultNow().notNull()});
export const purchases = pgTable('purchases', {id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),contentId:text('content_id').notNull().references(()=>contents.id),providerId:text('provider_id').notNull().unique(),amount:integer('amount').notNull(),status:text('status').notNull(),createdAt:timestamp('created_at').defaultNow().notNull()});
export const settings = pgTable('settings', {key:text('key').primaryKey(),value:jsonb('value').$type<Record<string, unknown>>().notNull()});
export const activity = pgTable('activity', {id:text('id').primaryKey(),userId:text('user_id'),action:text('action').notNull(),details:text('details').notNull().default(''),createdAt:timestamp('created_at').defaultNow().notNull()});
export const messages = pgTable('messages', {id:text('id').primaryKey(),name:text('name').notNull(),email:text('email').notNull(),subject:text('subject').notNull(),message:text('message').notNull(),createdAt:timestamp('created_at').defaultNow().notNull()});
export const resets = pgTable('password_resets', {token:text('token').primaryKey(),userId:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),expiresAt:timestamp('expires_at').notNull()});
export const announcements = pgTable('announcements',{id:text('id').primaryKey(),title:text('title').notNull(),body:text('body').notNull(),section:text('section').notNull().default('community'),createdAt:timestamp('created_at').defaultNow().notNull()});
export const rateLimits = pgTable('rate_limits',{key:text('key').primaryKey(),hits:integer('hits').notNull().default(1),resetAt:timestamp('reset_at').notNull()});
