import Link from 'next/link';
import { redirect } from 'next/navigation';
import { db } from '@/db';
import { users,activity,downloads,purchases,messages } from '@/db/schema';
import { eq,desc } from 'drizzle-orm';
import { getUser,adminRoles,creatorRoles } from '@/lib/auth';
import { getContent,getCategories,getStats,getSettings,getLibrary } from '@/lib/data';
import { ContentCard } from './content';
import { ContentManager,SettingsEditor,UserManager,CategoryManager,AnnouncementForm } from './management';
import { Uploader } from './uploader';
import { BecomeCreator,ProfileForm } from './forms';
import { EmptyState } from './ui';
import { LayoutDashboard,Layers3,Upload,BarChart3,Wallet,UserRound,Settings,Download,Heart,ShoppingBag,Bell,ArrowUpRight,Sparkles,Users,Tag,Globe,Gamepad2,Clock,ShieldCheck,CheckCircle2,Mail,Activity,Eye } from 'lucide-react';
export async function Dashboard({mode,tab='overview'}:{mode:string;tab?:string}){const user=await getUser();if(!user)redirect('/login');const isAdmin=adminRoles.includes(user.role),isCreator=creatorRoles.includes(user.role);if(mode==='admin'&&!isAdmin)return <div className="container error-page"><span>403</span><h1>This space is protected.</h1><p>Only authorized administrators can enter the creator control center.</p><div className="hero-buttons"><Link href="/dashboard" className="button secondary">Go to your dashboard<ArrowUpRight size={16}/></Link></div></div>;if(mode==='creator'&&!isCreator)return <div className="container page-section"><div className="page-heading"><div className="eyebrow"><span/>YOUR IDEAS DESERVE A HOME</div><h1>Make your mark<span className="red">.</span></h1><p>A free creator profile. Your own content library. A whole new world of possibilities.</p></div><div className="creator-callout"><Sparkles size={35}/><div><h3>Ready to put your work out there?</h3><p>Become a creator and start uploading. Every submission is reviewed before publishing.</p></div><BecomeCreator/></div></div>;
 const admin=mode==='admin',creator=mode==='creator',base=admin?'/admin':creator?'/creator':'/dashboard';const [allItems,categories,library,stats]=await Promise.all([getContent(admin?{all:true}:creator?{all:true,creator:user.id}:{}),getCategories(),getLibrary(user.id),getStats()]);const links=admin?[['Overview','overview',LayoutDashboard],['Content','content',Layers3],['Upload','upload',Upload],['Free Stuff','free',Download],['Paid Stuff','paid',ShoppingBag],['Pending','pending',Clock],['Users & Creators','users',Users],['Orders','orders',Wallet],['Downloads','downloads',Download],['Categories','categories',Tag],['Homepage','homepage',Globe],['Community','community',Users],['SMP / Season 5','season',Gamepad2],['Analytics','analytics',BarChart3],['Activity','activity',Activity],['Inbox','inbox',Mail],['Settings','settings',Settings]]:creator?[['Overview','overview',LayoutDashboard],['My Content','content',Layers3],['Upload','upload',Upload],['Analytics','analytics',BarChart3],['Earnings','earnings',Wallet],['Profile','profile',UserRound],['Settings','settings',Settings]]:[['Overview','overview',LayoutDashboard],['My Downloads','downloads',Download],['Favorites','favorites',Heart],['Purchases','purchases',ShoppingBag],['Notifications','notifications',Bell],['Profile','profile',UserRound],['Settings','settings',Settings]];
 const title=tab==='overview'?(admin?'HOMELAND CREATOR PANEL':creator?'Your creative control center.':`Welcome home, ${user.name.split(' ')[0]}.`):String(links.find(l=>l[1]===tab)?.[0]||'Your account');const totals=admin?[{label:'Total content',value:stats.total,icon:Layers3},{label:'Total downloads',value:stats.downloads,icon:Download},{label:'Community members',value:stats.users,icon:Users},{label:'Creators',value:stats.creators,icon:Sparkles}]:creator?[{label:'Total uploads',value:allItems.length,icon:Layers3},{label:'Downloads',value:allItems.reduce((a,i)=>a+i.downloads,0),icon:Download},{label:'Content views',value:allItems.reduce((a,i)=>a+i.views,0),icon:Eye},{label:'Published',value:allItems.filter(i=>i.status==='published').length,icon:CheckCircle2}]:[{label:'Your downloads',value:library.history.length,icon:Download},{label:'Saved favorites',value:library.saved.length,icon:Heart},{label:'Purchased resources',value:library.orders.length,icon:ShoppingBag},{label:'Free to discover',value:stats.free,icon:Sparkles}];
 let panel:React.ReactNode=null;
 if(tab==='upload'&&(admin||creator))panel=<Uploader categories={categories} admin={admin}/>;
 else if(['content','free','paid','pending'].includes(tab)&&(admin||creator))panel=<div className="dashboard-panel"><h2>{tab==='pending'?'Waiting for a little green light.':'Your work, all in one place.'}</h2><p>Manage, improve, and share your creations with the world.</p><ContentManager items={allItems.filter(i=>tab==='free'?i.price===0:tab==='paid'?i.price>0:tab==='pending'?i.status==='pending':true)} categories={categories} admin={admin}/></div>;
 else if(tab==='users'&&admin){const data=await db.select({id:users.id,name:users.name,username:users.username,email:users.email,role:users.role,suspended:users.suspended,createdAt:users.createdAt}).from(users).orderBy(desc(users.createdAt));panel=<div className="dashboard-panel"><h2>The people who make HOMELAND.</h2><UserManager users={data}/></div>;}
 else if(tab==='categories'&&admin)panel=<div className="dashboard-panel"><h2>Organize a world of possibilities.</h2><p>Create, edit and reorder the resource categories.</p><CategoryManager categories={categories}/></div>;
 else if(['homepage','season','community','faq'].includes(tab)&&admin){const value=await getSettings(tab);panel=<><div className="dashboard-panel"><h2>{tab==='season'?'The next chapter starts here.':tab==='homepage'?'Make a great first impression.':'Your community, connected.'}</h2><p>These settings are stored in the database and update the public website.</p><SettingsEditor key={tab} section={tab} value={value}/></div>{tab==='homepage'&&<div className="dashboard-panel"><h2>Frequently asked questions</h2><p>Manage the homepage questions and answers.</p><SettingsEditor section="faq" value={await getSettings('faq')}/></div>}{tab==='community'&&<div className="dashboard-panel"><h2>A little news for your community.</h2><AnnouncementForm/></div>}</>;}
 else if(tab==='activity'&&admin){const logs=await db.select().from(activity).orderBy(desc(activity.createdAt)).limit(100);panel=<div className="dashboard-panel"><h2>Every change has a story.</h2>{logs.map(log=><div className="activity-item" key={log.id}><Activity size={17}/><div><strong>{log.action.replaceAll('.',' · ')}</strong><p>{log.details||'Account activity'}</p></div><time>{log.createdAt.toLocaleString()}</time></div>)}{!logs.length&&<p className="notification-empty">No activity has been recorded yet.</p>}</div>;}
 else if(tab==='inbox'&&admin){const inbox=await db.select().from(messages).orderBy(desc(messages.createdAt)).limit(100);panel=<div className="dashboard-panel"><h2>Notes from your community.</h2>{inbox.map(m=><div className="announcement" key={m.id}><div className="eyebrow">{m.name} · {m.createdAt.toLocaleDateString()}</div><h3>{m.subject}</h3><p>{m.message}</p><a className="text-link" href={'mailto:'+m.email}>Reply to {m.email}<ArrowUpRight size={13}/></a></div>)}{!inbox.length&&<p className="notification-empty">No messages yet. Contact form submissions will appear here.</p>}</div>;}
 else if(['profile','settings'].includes(tab))panel=<><div className="dashboard-panel"><h2>Your little corner of HOMELAND.</h2><p>Let the community get to know the creator behind the work.</p><ProfileForm user={user}/></div><div className="dashboard-panel"><h2>Account security</h2><p>Your sessions use secure, HTTP-only cookies. Passwords are hashed with scrypt.</p><Link href="/forgot-password" className="button secondary">Reset your password<ShieldCheck size={15}/></Link></div>{admin&&<div className="dashboard-panel"><h2>Platform connections</h2><p>Storage: {process.env.S3_BUCKET?'S3-compatible private object storage':'Private local storage (configure S3 for durable production storage)'}</p><p>Email: {process.env.RESEND_API_KEY&&process.env.EMAIL_FROM?'Reset email configured':'Not configured — password reset delivery is unavailable'}</p><p>Payments: Purchasing is currently unavailable. No unverified payments are accepted.</p></div>}</>;
 else if(tab==='analytics'||tab==='overview'){
 const events=admin?await db.select().from(downloads).orderBy(desc(downloads.createdAt)).limit(1000):creator?(await db.select().from(downloads).orderBy(desc(downloads.createdAt)).limit(1000)).filter(d=>allItems.some(i=>i.id===d.contentId)):[];const days=Array.from({length:7},(_,i)=>{const date=new Date();date.setDate(date.getDate()-6+i);return {label:date.toLocaleDateString('en-US',{weekday:'short'}),value:events.filter(e=>e.createdAt.toDateString()===date.toDateString()).length};});const max=Math.max(...days.map(d=>d.value),1);
 panel=<><div className="dashboard-stat-grid">{totals.map(s=><div className="dashboard-stat" key={s.label}><div>{s.label}<s.icon size={17}/></div><strong>{s.value.toLocaleString()}</strong><span>Live from your platform</span></div>)}</div>{(admin||creator)&&<div className="dashboard-panel"><div className="section-head"><div><h2>A little momentum.</h2><p>Downloads over the past seven days.</p></div><span className="status">Live data</span></div><div className="chart">{days.map((d,i)=><div key={i} className="chart-bar" style={{height:Math.max(d.value/max*125,3)}}><span>{d.value}</span></div>)}</div><div className="chart-labels">{days.map((d,i)=><span key={i}>{d.label}</span>)}</div>{events.length===0&&<p style={{fontSize:10,margin:'22px 0 0'}}>Your story is just beginning. Real downloads will appear here as your community grows.</p>}</div>}{!admin&&!creator&&<div className="creator-callout"><Sparkles size={30}/><div><h3>Your ideas deserve a home.</h3><p>Become a creator. Share your work. Make your mark.</p></div><BecomeCreator/></div>}<div className="dashboard-panel"><div className="section-head"><h2>{admin||creator?'Your latest creations.':'A little inspiration, just for you.'}</h2><Link href={admin||creator?base+'?tab=content':'/free'} className="text-link">Explore all<ArrowUpRight size={14}/></Link></div>{admin||creator?<ContentManager items={allItems.slice(0,5)} categories={categories} admin={admin}/>:<div className="content-grid">{allItems.slice(0,3).map(i=><ContentCard item={i} key={i.id} saved={library.saved.some(s=>s.id===i.id)}/>)}</div>}</div></>;
 }
 else if(tab==='favorites'){const saved=allItems.filter(i=>library.saved.some(s=>s.id===i.id));panel=saved.length?<div className="content-grid">{saved.map(i=><ContentCard item={i} key={i.id} saved/>)}</div>:<EmptyState title="A collection waiting to happen." description="Tap the heart on any resource to save a little inspiration for later."/>;}
 else if(tab==='downloads'){if(admin){const events=await db.select().from(downloads).orderBy(desc(downloads.createdAt)).limit(100);panel=<div className="dashboard-panel"><h2>Every download, a new possibility.</h2><div className="table-scroll"><table><thead><tr><th>Resource</th><th>Member</th><th>Date</th></tr></thead><tbody>{events.map(e=><tr key={e.id}><td>{allItems.find(i=>i.id===e.contentId)?.title||e.contentId}</td><td>{e.userId||'Guest download'}</td><td>{e.createdAt.toLocaleString()}</td></tr>)}</tbody></table>{!events.length&&<p className="notification-empty">No downloads yet.</p>}</div></div>;}else{const history=allItems.filter(i=>library.history.some(h=>h.id===i.id));panel=history.length?<div className="content-grid">{history.map(i=><ContentCard key={i.id} item={i}/>)}</div>:<EmptyState title="Your creative journey starts here." description="Your downloaded resources will be ready to rediscover here."/>;}}
 else if(['orders','purchases','earnings'].includes(tab)){const orders=admin?await db.select().from(purchases).orderBy(desc(purchases.createdAt)).limit(100):library.orders;panel=<div className="dashboard-panel"><h2>{tab==='earnings'?'Good work deserves good things.':'Your premium collection.'}</h2><p>Purchasing is currently unavailable. Only verified provider transactions can grant access.</p>{orders.length?<div className="table-scroll"><table><thead><tr><th>Order</th><th>Amount</th><th>Status</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>{o.id}</td><td>{(o.amount/100).toFixed(2)}</td><td>{o.status}</td></tr>)}</tbody></table></div>:<EmptyState title="No transactions yet." description="When verified purchases are available, your transaction history will appear here." href="/paid" label="Discover Premium"/>}</div>;}
 else if(tab==='notifications')panel=<div className="dashboard-panel"><h2>You’re all caught up.</h2><p className="notification-empty">No account notifications at the moment.</p><Link href="/community" className="text-link">See community announcements<ArrowUpRight size={15}/></Link></div>;
 else panel=<EmptyState title="Let’s get you back on track." href={base} label="Dashboard overview"/>;
 return <div className="dashboard-layout"><aside className="dashboard-sidebar"><div className="sidebar-label">{admin?'CREATOR CONTROL CENTER':creator?'YOUR CREATIVE STUDIO':'YOUR HOMELAND'}</div>{links.map(([label,key,Component])=>{const C=Component as typeof LayoutDashboard;return <Link className={tab===key?'active':''} key={String(key)} href={base+'?tab='+key}><C size={16}/>{String(label)}</Link>;})}<div className="sidebar-user"><div className="mini-avatar">{user.name[0]}</div><div><strong>{user.name}</strong><span>{user.role}</span></div></div></aside><div className="dashboard-content"><div className="dashboard-header"><div><div className="eyebrow"><span/>{admin?'MANAGE YOUR PLATFORM':creator?'YOUR WORK. YOUR WORLD.':'A HOME FOR YOUR NEXT BIG IDEA'}</div><h1>{title}</h1><p>{admin?'A little oversight. A world of possibilities.':creator?'Everything you need to bring your ideas to life.':'Your resources, your favorites, your next great creation.'}</p></div>{(admin||creator)&&tab!=='upload'&&<Link href={base+'?tab=upload'} className="button primary"><Upload size={14}/>Upload content<ArrowUpRight size={14}/></Link>}</div>{panel}</div></div>;
}
